/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Allowance
 */
@JsonPropertyOrder({
  Allowance.JSON_PROPERTY_CAN_CREATE_AMENDMENT,
  Allowance.JSON_PROPERTY_CAN_VIEW_AMENDMENT
})
@JsonTypeName("Allowance")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class Allowance {
  public static final String JSON_PROPERTY_CAN_CREATE_AMENDMENT = "canCreateAmendment";
  private Boolean canCreateAmendment;

  public static final String JSON_PROPERTY_CAN_VIEW_AMENDMENT = "canViewAmendment";
  private Boolean canViewAmendment;


  public Allowance canCreateAmendment(Boolean canCreateAmendment) {
    
    this.canCreateAmendment = canCreateAmendment;
    return this;
  }

   /**
   * Get canCreateAmendment
   * @return canCreateAmendment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAN_CREATE_AMENDMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanCreateAmendment() {
    return canCreateAmendment;
  }


  public void setCanCreateAmendment(Boolean canCreateAmendment) {
    this.canCreateAmendment = canCreateAmendment;
  }


  public Allowance canViewAmendment(Boolean canViewAmendment) {
    
    this.canViewAmendment = canViewAmendment;
    return this;
  }

   /**
   * Get canViewAmendment
   * @return canViewAmendment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAN_VIEW_AMENDMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanViewAmendment() {
    return canViewAmendment;
  }


  public void setCanViewAmendment(Boolean canViewAmendment) {
    this.canViewAmendment = canViewAmendment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Allowance allowance = (Allowance) o;
    return Objects.equals(this.canCreateAmendment, allowance.canCreateAmendment) &&
        Objects.equals(this.canViewAmendment, allowance.canViewAmendment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canCreateAmendment, canViewAmendment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Allowance {\n");
    sb.append("    canCreateAmendment: ").append(toIndentedString(canCreateAmendment)).append("\n");
    sb.append("    canViewAmendment: ").append(toIndentedString(canViewAmendment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

