/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ContractReferenceData
 */
@JsonPropertyOrder({
  ContractReferenceData.JSON_PROPERTY_AGREEMENT_ID,
  ContractReferenceData.JSON_PROPERTY_AGREEMENT_TYPE,
  ContractReferenceData.JSON_PROPERTY_END_DATE,
  ContractReferenceData.JSON_PROPERTY_LOT_NAME,
  ContractReferenceData.JSON_PROPERTY_REFERENCE,
  ContractReferenceData.JSON_PROPERTY_START_DATE
})
@JsonTypeName("ContractReferenceData")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class ContractReferenceData {
  public static final String JSON_PROPERTY_AGREEMENT_ID = "agreementId";
  private Long agreementId;

  public static final String JSON_PROPERTY_AGREEMENT_TYPE = "agreementType";
  private String agreementType;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private OffsetDateTime endDate;

  public static final String JSON_PROPERTY_LOT_NAME = "lotName";
  private String lotName;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private String reference;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private OffsetDateTime startDate;


  public ContractReferenceData agreementId(Long agreementId) {
    
    this.agreementId = agreementId;
    return this;
  }

   /**
   * Get agreementId
   * @return agreementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AGREEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAgreementId() {
    return agreementId;
  }


  public void setAgreementId(Long agreementId) {
    this.agreementId = agreementId;
  }


  public ContractReferenceData agreementType(String agreementType) {
    
    this.agreementType = agreementType;
    return this;
  }

   /**
   * Get agreementType
   * @return agreementType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AGREEMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgreementType() {
    return agreementType;
  }


  public void setAgreementType(String agreementType) {
    this.agreementType = agreementType;
  }


  public ContractReferenceData endDate(OffsetDateTime endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getEndDate() {
    return endDate;
  }


  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public ContractReferenceData lotName(String lotName) {
    
    this.lotName = lotName;
    return this;
  }

   /**
   * Get lotName
   * @return lotName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLotName() {
    return lotName;
  }


  public void setLotName(String lotName) {
    this.lotName = lotName;
  }


  public ContractReferenceData reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    this.reference = reference;
  }


  public ContractReferenceData startDate(OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractReferenceData contractReferenceData = (ContractReferenceData) o;
    return Objects.equals(this.agreementId, contractReferenceData.agreementId) &&
        Objects.equals(this.agreementType, contractReferenceData.agreementType) &&
        Objects.equals(this.endDate, contractReferenceData.endDate) &&
        Objects.equals(this.lotName, contractReferenceData.lotName) &&
        Objects.equals(this.reference, contractReferenceData.reference) &&
        Objects.equals(this.startDate, contractReferenceData.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreementId, agreementType, endDate, lotName, reference, startDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractReferenceData {\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("    agreementType: ").append(toIndentedString(agreementType)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    lotName: ").append(toIndentedString(lotName)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

