/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kirona.spring.cloudmarketplace.client.po.model.GoodsReceiptLine;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * GoodsReceipt
 */
@JsonPropertyOrder({
  GoodsReceipt.JSON_PROPERTY_AMENDED_DATE,
  GoodsReceipt.JSON_PROPERTY_CREATED_DATE,
  GoodsReceipt.JSON_PROPERTY_DELIVERY_NOTE,
  GoodsReceipt.JSON_PROPERTY_DESCRIPTION,
  GoodsReceipt.JSON_PROPERTY_GLOBAL,
  GoodsReceipt.JSON_PROPERTY_ID,
  GoodsReceipt.JSON_PROPERTY_LINES,
  GoodsReceipt.JSON_PROPERTY_PURCHASE_ORDER_ID,
  GoodsReceipt.JSON_PROPERTY_PURCHASE_ORDER_NUMBER,
  GoodsReceipt.JSON_PROPERTY_RECEIVED_DATE,
  GoodsReceipt.JSON_PROPERTY_RECEIVER
})
@JsonTypeName("GoodsReceipt")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class GoodsReceipt {
  public static final String JSON_PROPERTY_AMENDED_DATE = "amendedDate";
  private OffsetDateTime amendedDate;

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  private OffsetDateTime createdDate;

  public static final String JSON_PROPERTY_DELIVERY_NOTE = "deliveryNote";
  private String deliveryNote;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_GLOBAL = "global";
  private Boolean global;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_LINES = "lines";
  private List<GoodsReceiptLine> lines = null;

  public static final String JSON_PROPERTY_PURCHASE_ORDER_ID = "purchaseOrderId";
  private Long purchaseOrderId;

  public static final String JSON_PROPERTY_PURCHASE_ORDER_NUMBER = "purchaseOrderNumber";
  private String purchaseOrderNumber;

  public static final String JSON_PROPERTY_RECEIVED_DATE = "receivedDate";
  private OffsetDateTime receivedDate;

  public static final String JSON_PROPERTY_RECEIVER = "receiver";
  private String receiver;


  public GoodsReceipt amendedDate(OffsetDateTime amendedDate) {
    
    this.amendedDate = amendedDate;
    return this;
  }

   /**
   * Get amendedDate
   * @return amendedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMENDED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getAmendedDate() {
    return amendedDate;
  }


  public void setAmendedDate(OffsetDateTime amendedDate) {
    this.amendedDate = amendedDate;
  }


  public GoodsReceipt createdDate(OffsetDateTime createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }


  public GoodsReceipt deliveryNote(String deliveryNote) {
    
    this.deliveryNote = deliveryNote;
    return this;
  }

   /**
   * Get deliveryNote
   * @return deliveryNote
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELIVERY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeliveryNote() {
    return deliveryNote;
  }


  public void setDeliveryNote(String deliveryNote) {
    this.deliveryNote = deliveryNote;
  }


  public GoodsReceipt description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public GoodsReceipt global(Boolean global) {
    
    this.global = global;
    return this;
  }

   /**
   * Get global
   * @return global
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GLOBAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getGlobal() {
    return global;
  }


  public void setGlobal(Boolean global) {
    this.global = global;
  }


  public GoodsReceipt id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public GoodsReceipt lines(List<GoodsReceiptLine> lines) {
    
    this.lines = lines;
    return this;
  }

  public GoodsReceipt addLinesItem(GoodsReceiptLine linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GoodsReceiptLine> getLines() {
    return lines;
  }


  public void setLines(List<GoodsReceiptLine> lines) {
    this.lines = lines;
  }


  public GoodsReceipt purchaseOrderId(Long purchaseOrderId) {
    
    this.purchaseOrderId = purchaseOrderId;
    return this;
  }

   /**
   * Get purchaseOrderId
   * @return purchaseOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PURCHASE_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPurchaseOrderId() {
    return purchaseOrderId;
  }


  public void setPurchaseOrderId(Long purchaseOrderId) {
    this.purchaseOrderId = purchaseOrderId;
  }


  public GoodsReceipt purchaseOrderNumber(String purchaseOrderNumber) {
    
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Get purchaseOrderNumber
   * @return purchaseOrderNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PURCHASE_ORDER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }


  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }


  public GoodsReceipt receivedDate(OffsetDateTime receivedDate) {
    
    this.receivedDate = receivedDate;
    return this;
  }

   /**
   * Get receivedDate
   * @return receivedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getReceivedDate() {
    return receivedDate;
  }


  public void setReceivedDate(OffsetDateTime receivedDate) {
    this.receivedDate = receivedDate;
  }


  public GoodsReceipt receiver(String receiver) {
    
    this.receiver = receiver;
    return this;
  }

   /**
   * Get receiver
   * @return receiver
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReceiver() {
    return receiver;
  }


  public void setReceiver(String receiver) {
    this.receiver = receiver;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodsReceipt goodsReceipt = (GoodsReceipt) o;
    return Objects.equals(this.amendedDate, goodsReceipt.amendedDate) &&
        Objects.equals(this.createdDate, goodsReceipt.createdDate) &&
        Objects.equals(this.deliveryNote, goodsReceipt.deliveryNote) &&
        Objects.equals(this.description, goodsReceipt.description) &&
        Objects.equals(this.global, goodsReceipt.global) &&
        Objects.equals(this.id, goodsReceipt.id) &&
        Objects.equals(this.lines, goodsReceipt.lines) &&
        Objects.equals(this.purchaseOrderId, goodsReceipt.purchaseOrderId) &&
        Objects.equals(this.purchaseOrderNumber, goodsReceipt.purchaseOrderNumber) &&
        Objects.equals(this.receivedDate, goodsReceipt.receivedDate) &&
        Objects.equals(this.receiver, goodsReceipt.receiver);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amendedDate, createdDate, deliveryNote, description, global, id, lines, purchaseOrderId, purchaseOrderNumber, receivedDate, receiver);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodsReceipt {\n");
    sb.append("    amendedDate: ").append(toIndentedString(amendedDate)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    deliveryNote: ").append(toIndentedString(deliveryNote)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    global: ").append(toIndentedString(global)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    purchaseOrderId: ").append(toIndentedString(purchaseOrderId)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    receivedDate: ").append(toIndentedString(receivedDate)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

