/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * GoodsReceiptLine
 */
@JsonPropertyOrder({
  GoodsReceiptLine.JSON_PROPERTY_DISPUTED_QUANTITY,
  GoodsReceiptLine.JSON_PROPERTY_ID,
  GoodsReceiptLine.JSON_PROPERTY_ORDER_LINE_ID,
  GoodsReceiptLine.JSON_PROPERTY_QUANTITY
})
@JsonTypeName("GoodsReceiptLine")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class GoodsReceiptLine {
  public static final String JSON_PROPERTY_DISPUTED_QUANTITY = "disputedQuantity";
  private BigDecimal disputedQuantity;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_ORDER_LINE_ID = "orderLineId";
  private Long orderLineId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private BigDecimal quantity;


  public GoodsReceiptLine disputedQuantity(BigDecimal disputedQuantity) {
    
    this.disputedQuantity = disputedQuantity;
    return this;
  }

   /**
   * Get disputedQuantity
   * @return disputedQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDisputedQuantity() {
    return disputedQuantity;
  }


  public void setDisputedQuantity(BigDecimal disputedQuantity) {
    this.disputedQuantity = disputedQuantity;
  }


  public GoodsReceiptLine id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public GoodsReceiptLine orderLineId(Long orderLineId) {
    
    this.orderLineId = orderLineId;
    return this;
  }

   /**
   * Get orderLineId
   * @return orderLineId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDER_LINE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOrderLineId() {
    return orderLineId;
  }


  public void setOrderLineId(Long orderLineId) {
    this.orderLineId = orderLineId;
  }


  public GoodsReceiptLine quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getQuantity() {
    return quantity;
  }


  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoodsReceiptLine goodsReceiptLine = (GoodsReceiptLine) o;
    return Objects.equals(this.disputedQuantity, goodsReceiptLine.disputedQuantity) &&
        Objects.equals(this.id, goodsReceiptLine.id) &&
        Objects.equals(this.orderLineId, goodsReceiptLine.orderLineId) &&
        Objects.equals(this.quantity, goodsReceiptLine.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disputedQuantity, id, orderLineId, quantity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodsReceiptLine {\n");
    sb.append("    disputedQuantity: ").append(toIndentedString(disputedQuantity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderLineId: ").append(toIndentedString(orderLineId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

