/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kirona.spring.cloudmarketplace.client.po.model.Allowance;
import com.kirona.spring.cloudmarketplace.client.po.model.BillingInfo;
import com.kirona.spring.cloudmarketplace.client.po.model.Buyer;
import com.kirona.spring.cloudmarketplace.client.po.model.FreeFormatDeliveryInfo;
import com.kirona.spring.cloudmarketplace.client.po.model.PrintInfo;
import com.kirona.spring.cloudmarketplace.client.po.model.PurchaseOrderLine;
import com.kirona.spring.cloudmarketplace.client.po.model.ShippingInfo;
import com.kirona.spring.cloudmarketplace.client.po.model.Supplier;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PurchaseOrder
 */
@JsonPropertyOrder({
  PurchaseOrder.JSON_PROPERTY_ALLOWANCE,
  PurchaseOrder.JSON_PROPERTY_AMENDMENT_IN_PROGRESS,
  PurchaseOrder.JSON_PROPERTY_AMENDMENTS,
  PurchaseOrder.JSON_PROPERTY_BILLING_INFO,
  PurchaseOrder.JSON_PROPERTY_BUYER,
  PurchaseOrder.JSON_PROPERTY_BUYER_NUMBER,
  PurchaseOrder.JSON_PROPERTY_COMMENTS,
  PurchaseOrder.JSON_PROPERTY_DATE,
  PurchaseOrder.JSON_PROPERTY_FREE_FORMAT_DELIVERY_INFO,
  PurchaseOrder.JSON_PROPERTY_GRAND_TOTAL,
  PurchaseOrder.JSON_PROPERTY_ID,
  PurchaseOrder.JSON_PROPERTY_LINES,
  PurchaseOrder.JSON_PROPERTY_NET_TOTAL,
  PurchaseOrder.JSON_PROPERTY_NUMBER,
  PurchaseOrder.JSON_PROPERTY_PAYMENT_INFO,
  PurchaseOrder.JSON_PROPERTY_PRINT_INFO,
  PurchaseOrder.JSON_PROPERTY_REQUISITION_ID,
  PurchaseOrder.JSON_PROPERTY_SENT_TO_SUPPLIER_DATE,
  PurchaseOrder.JSON_PROPERTY_SHIPPING_INFO,
  PurchaseOrder.JSON_PROPERTY_STATUS,
  PurchaseOrder.JSON_PROPERTY_SUPPLIER,
  PurchaseOrder.JSON_PROPERTY_TAX_TOTAL
})
@JsonTypeName("PurchaseOrder")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class PurchaseOrder {
  public static final String JSON_PROPERTY_ALLOWANCE = "allowance";
  private Allowance allowance;

  public static final String JSON_PROPERTY_AMENDMENT_IN_PROGRESS = "amendmentInProgress";
  private String amendmentInProgress;

  public static final String JSON_PROPERTY_AMENDMENTS = "amendments";
  private List<String> amendments = null;

  public static final String JSON_PROPERTY_BILLING_INFO = "billingInfo";
  private BillingInfo billingInfo;

  public static final String JSON_PROPERTY_BUYER = "buyer";
  private Buyer buyer;

  public static final String JSON_PROPERTY_BUYER_NUMBER = "buyerNumber";
  private String buyerNumber;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private String comments;

  public static final String JSON_PROPERTY_DATE = "date";
  private OffsetDateTime date;

  public static final String JSON_PROPERTY_FREE_FORMAT_DELIVERY_INFO = "freeFormatDeliveryInfo";
  private FreeFormatDeliveryInfo freeFormatDeliveryInfo;

  public static final String JSON_PROPERTY_GRAND_TOTAL = "grandTotal";
  private BigDecimal grandTotal;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_LINES = "lines";
  private List<PurchaseOrderLine> lines = null;

  public static final String JSON_PROPERTY_NET_TOTAL = "netTotal";
  private BigDecimal netTotal;

  public static final String JSON_PROPERTY_NUMBER = "number";
  private String number;

  public static final String JSON_PROPERTY_PAYMENT_INFO = "paymentInfo";
  private String paymentInfo;

  public static final String JSON_PROPERTY_PRINT_INFO = "printInfo";
  private PrintInfo printInfo;

  public static final String JSON_PROPERTY_REQUISITION_ID = "requisitionId";
  private String requisitionId;

  public static final String JSON_PROPERTY_SENT_TO_SUPPLIER_DATE = "sentToSupplierDate";
  private OffsetDateTime sentToSupplierDate;

  public static final String JSON_PROPERTY_SHIPPING_INFO = "shippingInfo";
  private ShippingInfo shippingInfo;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NOT_SUBMITTED("NOT_SUBMITTED"),
    
    PENDING_INTERNAL_APPROVAL("PENDING_INTERNAL_APPROVAL"),
    
    PENDING_EXTERNAL_APPROVAL("PENDING_EXTERNAL_APPROVAL"),
    
    PENDING_STORES_APPROVAL("PENDING_STORES_APPROVAL"),
    
    CANCELLED_BY_SUPPLIER("CANCELLED_BY_SUPPLIER"),
    
    CANCELLED_BY_BUYER("CANCELLED_BY_BUYER"),
    
    REJECTED_BY_BUYER("REJECTED_BY_BUYER"),
    
    REJECTED_EXTERNALLY("REJECTED_EXTERNALLY"),
    
    APPROVED_SUPPLIER_PENDING("APPROVED_SUPPLIER_PENDING"),
    
    APPROVED_SUPPLIER_ACCEPTED("APPROVED_SUPPLIER_ACCEPTED"),
    
    APPROVED_WAITING_TO_SEND("APPROVED_WAITING_TO_SEND"),
    
    APPROVED_EMAILED("APPROVED_EMAILED"),
    
    SHIPPED_PARTIAL("SHIPPED_PARTIAL"),
    
    SHIPPED("SHIPPED"),
    
    SHIPPED_STORES("SHIPPED_STORES"),
    
    RECEIVED("RECEIVED"),
    
    RECEIVED_PARTIAL("RECEIVED_PARTIAL"),
    
    IN_DISPUTE("IN_DISPUTE"),
    
    NOT_RECEIVED("NOT_RECEIVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUPPLIER = "supplier";
  private Supplier supplier;

  public static final String JSON_PROPERTY_TAX_TOTAL = "taxTotal";
  private BigDecimal taxTotal;


  public PurchaseOrder allowance(Allowance allowance) {
    
    this.allowance = allowance;
    return this;
  }

   /**
   * Get allowance
   * @return allowance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALLOWANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Allowance getAllowance() {
    return allowance;
  }


  public void setAllowance(Allowance allowance) {
    this.allowance = allowance;
  }


  public PurchaseOrder amendmentInProgress(String amendmentInProgress) {
    
    this.amendmentInProgress = amendmentInProgress;
    return this;
  }

   /**
   * Get amendmentInProgress
   * @return amendmentInProgress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMENDMENT_IN_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAmendmentInProgress() {
    return amendmentInProgress;
  }


  public void setAmendmentInProgress(String amendmentInProgress) {
    this.amendmentInProgress = amendmentInProgress;
  }


  public PurchaseOrder amendments(List<String> amendments) {
    
    this.amendments = amendments;
    return this;
  }

  public PurchaseOrder addAmendmentsItem(String amendmentsItem) {
    if (this.amendments == null) {
      this.amendments = new ArrayList<>();
    }
    this.amendments.add(amendmentsItem);
    return this;
  }

   /**
   * Get amendments
   * @return amendments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AMENDMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAmendments() {
    return amendments;
  }


  public void setAmendments(List<String> amendments) {
    this.amendments = amendments;
  }


  public PurchaseOrder billingInfo(BillingInfo billingInfo) {
    
    this.billingInfo = billingInfo;
    return this;
  }

   /**
   * Get billingInfo
   * @return billingInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BILLING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BillingInfo getBillingInfo() {
    return billingInfo;
  }


  public void setBillingInfo(BillingInfo billingInfo) {
    this.billingInfo = billingInfo;
  }


  public PurchaseOrder buyer(Buyer buyer) {
    
    this.buyer = buyer;
    return this;
  }

   /**
   * Get buyer
   * @return buyer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUYER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Buyer getBuyer() {
    return buyer;
  }


  public void setBuyer(Buyer buyer) {
    this.buyer = buyer;
  }


  public PurchaseOrder buyerNumber(String buyerNumber) {
    
    this.buyerNumber = buyerNumber;
    return this;
  }

   /**
   * Get buyerNumber
   * @return buyerNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_BUYER_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuyerNumber() {
    return buyerNumber;
  }


  public void setBuyerNumber(String buyerNumber) {
    this.buyerNumber = buyerNumber;
  }


  public PurchaseOrder comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public PurchaseOrder date(OffsetDateTime date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDate() {
    return date;
  }


  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  public PurchaseOrder freeFormatDeliveryInfo(FreeFormatDeliveryInfo freeFormatDeliveryInfo) {
    
    this.freeFormatDeliveryInfo = freeFormatDeliveryInfo;
    return this;
  }

   /**
   * Get freeFormatDeliveryInfo
   * @return freeFormatDeliveryInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FREE_FORMAT_DELIVERY_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FreeFormatDeliveryInfo getFreeFormatDeliveryInfo() {
    return freeFormatDeliveryInfo;
  }


  public void setFreeFormatDeliveryInfo(FreeFormatDeliveryInfo freeFormatDeliveryInfo) {
    this.freeFormatDeliveryInfo = freeFormatDeliveryInfo;
  }


  public PurchaseOrder grandTotal(BigDecimal grandTotal) {
    
    this.grandTotal = grandTotal;
    return this;
  }

   /**
   * Get grandTotal
   * @return grandTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GRAND_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getGrandTotal() {
    return grandTotal;
  }


  public void setGrandTotal(BigDecimal grandTotal) {
    this.grandTotal = grandTotal;
  }


  public PurchaseOrder id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public PurchaseOrder lines(List<PurchaseOrderLine> lines) {
    
    this.lines = lines;
    return this;
  }

  public PurchaseOrder addLinesItem(PurchaseOrderLine linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PurchaseOrderLine> getLines() {
    return lines;
  }


  public void setLines(List<PurchaseOrderLine> lines) {
    this.lines = lines;
  }


  public PurchaseOrder netTotal(BigDecimal netTotal) {
    
    this.netTotal = netTotal;
    return this;
  }

   /**
   * Get netTotal
   * @return netTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNetTotal() {
    return netTotal;
  }


  public void setNetTotal(BigDecimal netTotal) {
    this.netTotal = netTotal;
  }


  public PurchaseOrder number(String number) {
    
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNumber() {
    return number;
  }


  public void setNumber(String number) {
    this.number = number;
  }


  public PurchaseOrder paymentInfo(String paymentInfo) {
    
    this.paymentInfo = paymentInfo;
    return this;
  }

   /**
   * Get paymentInfo
   * @return paymentInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PAYMENT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentInfo() {
    return paymentInfo;
  }


  public void setPaymentInfo(String paymentInfo) {
    this.paymentInfo = paymentInfo;
  }


  public PurchaseOrder printInfo(PrintInfo printInfo) {
    
    this.printInfo = printInfo;
    return this;
  }

   /**
   * Get printInfo
   * @return printInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRINT_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PrintInfo getPrintInfo() {
    return printInfo;
  }


  public void setPrintInfo(PrintInfo printInfo) {
    this.printInfo = printInfo;
  }


  public PurchaseOrder requisitionId(String requisitionId) {
    
    this.requisitionId = requisitionId;
    return this;
  }

   /**
   * Get requisitionId
   * @return requisitionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REQUISITION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequisitionId() {
    return requisitionId;
  }


  public void setRequisitionId(String requisitionId) {
    this.requisitionId = requisitionId;
  }


  public PurchaseOrder sentToSupplierDate(OffsetDateTime sentToSupplierDate) {
    
    this.sentToSupplierDate = sentToSupplierDate;
    return this;
  }

   /**
   * Get sentToSupplierDate
   * @return sentToSupplierDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SENT_TO_SUPPLIER_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSentToSupplierDate() {
    return sentToSupplierDate;
  }


  public void setSentToSupplierDate(OffsetDateTime sentToSupplierDate) {
    this.sentToSupplierDate = sentToSupplierDate;
  }


  public PurchaseOrder shippingInfo(ShippingInfo shippingInfo) {
    
    this.shippingInfo = shippingInfo;
    return this;
  }

   /**
   * Get shippingInfo
   * @return shippingInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ShippingInfo getShippingInfo() {
    return shippingInfo;
  }


  public void setShippingInfo(ShippingInfo shippingInfo) {
    this.shippingInfo = shippingInfo;
  }


  public PurchaseOrder status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public PurchaseOrder supplier(Supplier supplier) {
    
    this.supplier = supplier;
    return this;
  }

   /**
   * Get supplier
   * @return supplier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Supplier getSupplier() {
    return supplier;
  }


  public void setSupplier(Supplier supplier) {
    this.supplier = supplier;
  }


  public PurchaseOrder taxTotal(BigDecimal taxTotal) {
    
    this.taxTotal = taxTotal;
    return this;
  }

   /**
   * Get taxTotal
   * @return taxTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAX_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTaxTotal() {
    return taxTotal;
  }


  public void setTaxTotal(BigDecimal taxTotal) {
    this.taxTotal = taxTotal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrder purchaseOrder = (PurchaseOrder) o;
    return Objects.equals(this.allowance, purchaseOrder.allowance) &&
        Objects.equals(this.amendmentInProgress, purchaseOrder.amendmentInProgress) &&
        Objects.equals(this.amendments, purchaseOrder.amendments) &&
        Objects.equals(this.billingInfo, purchaseOrder.billingInfo) &&
        Objects.equals(this.buyer, purchaseOrder.buyer) &&
        Objects.equals(this.buyerNumber, purchaseOrder.buyerNumber) &&
        Objects.equals(this.comments, purchaseOrder.comments) &&
        Objects.equals(this.date, purchaseOrder.date) &&
        Objects.equals(this.freeFormatDeliveryInfo, purchaseOrder.freeFormatDeliveryInfo) &&
        Objects.equals(this.grandTotal, purchaseOrder.grandTotal) &&
        Objects.equals(this.id, purchaseOrder.id) &&
        Objects.equals(this.lines, purchaseOrder.lines) &&
        Objects.equals(this.netTotal, purchaseOrder.netTotal) &&
        Objects.equals(this.number, purchaseOrder.number) &&
        Objects.equals(this.paymentInfo, purchaseOrder.paymentInfo) &&
        Objects.equals(this.printInfo, purchaseOrder.printInfo) &&
        Objects.equals(this.requisitionId, purchaseOrder.requisitionId) &&
        Objects.equals(this.sentToSupplierDate, purchaseOrder.sentToSupplierDate) &&
        Objects.equals(this.shippingInfo, purchaseOrder.shippingInfo) &&
        Objects.equals(this.status, purchaseOrder.status) &&
        Objects.equals(this.supplier, purchaseOrder.supplier) &&
        Objects.equals(this.taxTotal, purchaseOrder.taxTotal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowance, amendmentInProgress, amendments, billingInfo, buyer, buyerNumber, comments, date, freeFormatDeliveryInfo, grandTotal, id, lines, netTotal, number, paymentInfo, printInfo, requisitionId, sentToSupplierDate, shippingInfo, status, supplier, taxTotal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrder {\n");
    sb.append("    allowance: ").append(toIndentedString(allowance)).append("\n");
    sb.append("    amendmentInProgress: ").append(toIndentedString(amendmentInProgress)).append("\n");
    sb.append("    amendments: ").append(toIndentedString(amendments)).append("\n");
    sb.append("    billingInfo: ").append(toIndentedString(billingInfo)).append("\n");
    sb.append("    buyer: ").append(toIndentedString(buyer)).append("\n");
    sb.append("    buyerNumber: ").append(toIndentedString(buyerNumber)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    freeFormatDeliveryInfo: ").append(toIndentedString(freeFormatDeliveryInfo)).append("\n");
    sb.append("    grandTotal: ").append(toIndentedString(grandTotal)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    netTotal: ").append(toIndentedString(netTotal)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    paymentInfo: ").append(toIndentedString(paymentInfo)).append("\n");
    sb.append("    printInfo: ").append(toIndentedString(printInfo)).append("\n");
    sb.append("    requisitionId: ").append(toIndentedString(requisitionId)).append("\n");
    sb.append("    sentToSupplierDate: ").append(toIndentedString(sentToSupplierDate)).append("\n");
    sb.append("    shippingInfo: ").append(toIndentedString(shippingInfo)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    taxTotal: ").append(toIndentedString(taxTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

