/*
 * Purchase Orders API
 * REST API for purchase orders
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kirona.spring.cloudmarketplace.client.po.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.kirona.spring.cloudmarketplace.client.po.model.Attachment;
import com.kirona.spring.cloudmarketplace.client.po.model.ClassificationCode;
import com.kirona.spring.cloudmarketplace.client.po.model.ContractReferenceData;
import com.kirona.spring.cloudmarketplace.client.po.model.Currency;
import com.kirona.spring.cloudmarketplace.client.po.model.CustomField;
import com.kirona.spring.cloudmarketplace.client.po.model.ServiceInfo;
import com.kirona.spring.cloudmarketplace.client.po.model.TaxInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * PurchaseOrderLine
 */
@JsonPropertyOrder({
  PurchaseOrderLine.JSON_PROPERTY_ATTACHMENT,
  PurchaseOrderLine.JSON_PROPERTY_ATTENTION,
  PurchaseOrderLine.JSON_PROPERTY_ATTRIBUTES,
  PurchaseOrderLine.JSON_PROPERTY_CANCELLED_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_CATALOGUE_ITEM_ID,
  PurchaseOrderLine.JSON_PROPERTY_CATALOGUE_NUMBER,
  PurchaseOrderLine.JSON_PROPERTY_CATEGORY_NAME,
  PurchaseOrderLine.JSON_PROPERTY_CLASSIFICATION_CODE,
  PurchaseOrderLine.JSON_PROPERTY_COMMENTS,
  PurchaseOrderLine.JSON_PROPERTY_CONTRACT_REFERENCE_DATA,
  PurchaseOrderLine.JSON_PROPERTY_CURRENCY,
  PurchaseOrderLine.JSON_PROPERTY_CUSTOM_FIELDS,
  PurchaseOrderLine.JSON_PROPERTY_DATE_REQUIRED,
  PurchaseOrderLine.JSON_PROPERTY_DESCRIPTION,
  PurchaseOrderLine.JSON_PROPERTY_DISPUTED_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_EXTERNAL_COMMENTS,
  PurchaseOrderLine.JSON_PROPERTY_EXTERNAL_ID,
  PurchaseOrderLine.JSON_PROPERTY_GRAND_TOTAL,
  PurchaseOrderLine.JSON_PROPERTY_ID,
  PurchaseOrderLine.JSON_PROPERTY_JPPSG_CODE,
  PurchaseOrderLine.JSON_PROPERTY_LINE_TYPE_ID,
  PurchaseOrderLine.JSON_PROPERTY_MANUFACTURER,
  PurchaseOrderLine.JSON_PROPERTY_NET_TOTAL,
  PurchaseOrderLine.JSON_PROPERTY_NUMBER_OF_ALERTS_SENT,
  PurchaseOrderLine.JSON_PROPERTY_OLIGO_ID,
  PurchaseOrderLine.JSON_PROPERTY_ORDERED_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_PACK_SIZE,
  PurchaseOrderLine.JSON_PROPERTY_PART_NUMBER,
  PurchaseOrderLine.JSON_PROPERTY_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_RECEIVED_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_REQUISITIONER_EMAIL,
  PurchaseOrderLine.JSON_PROPERTY_REQUISITIONER_NAME,
  PurchaseOrderLine.JSON_PROPERTY_SERVICE_INFO,
  PurchaseOrderLine.JSON_PROPERTY_SHIPPED_QUANTITY,
  PurchaseOrderLine.JSON_PROPERTY_SUPPLIER_COMMENTS,
  PurchaseOrderLine.JSON_PROPERTY_SUPPLIER_PART_NUMBER,
  PurchaseOrderLine.JSON_PROPERTY_TAX_INFO,
  PurchaseOrderLine.JSON_PROPERTY_UNIT_OF_MEASURE,
  PurchaseOrderLine.JSON_PROPERTY_UNIT_PRICE
})
@JsonTypeName("PurchaseOrderLine")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-19T13:44:41.473Z[Europe/London]")
public class PurchaseOrderLine {
  public static final String JSON_PROPERTY_ATTACHMENT = "attachment";
  private Attachment attachment;

  public static final String JSON_PROPERTY_ATTENTION = "attention";
  private String attention;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private Object attributes;

  public static final String JSON_PROPERTY_CANCELLED_QUANTITY = "cancelledQuantity";
  private BigDecimal cancelledQuantity;

  public static final String JSON_PROPERTY_CATALOGUE_ITEM_ID = "catalogueItemId";
  private Long catalogueItemId;

  public static final String JSON_PROPERTY_CATALOGUE_NUMBER = "catalogueNumber";
  private String catalogueNumber;

  public static final String JSON_PROPERTY_CATEGORY_NAME = "categoryName";
  private String categoryName;

  public static final String JSON_PROPERTY_CLASSIFICATION_CODE = "classificationCode";
  private ClassificationCode classificationCode;

  public static final String JSON_PROPERTY_COMMENTS = "comments";
  private String comments;

  public static final String JSON_PROPERTY_CONTRACT_REFERENCE_DATA = "contractReferenceData";
  private ContractReferenceData contractReferenceData;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private Currency currency;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "customFields";
  private List<CustomField> customFields = null;

  public static final String JSON_PROPERTY_DATE_REQUIRED = "dateRequired";
  private OffsetDateTime dateRequired;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_DISPUTED_QUANTITY = "disputedQuantity";
  private BigDecimal disputedQuantity;

  public static final String JSON_PROPERTY_EXTERNAL_COMMENTS = "externalComments";
  private String externalComments;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "externalId";
  private String externalId;

  public static final String JSON_PROPERTY_GRAND_TOTAL = "grandTotal";
  private BigDecimal grandTotal;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_JPPSG_CODE = "jppsgCode";
  private String jppsgCode;

  public static final String JSON_PROPERTY_LINE_TYPE_ID = "lineTypeId";
  private Long lineTypeId;

  public static final String JSON_PROPERTY_MANUFACTURER = "manufacturer";
  private String manufacturer;

  public static final String JSON_PROPERTY_NET_TOTAL = "netTotal";
  private BigDecimal netTotal;

  public static final String JSON_PROPERTY_NUMBER_OF_ALERTS_SENT = "numberOfAlertsSent";
  private BigDecimal numberOfAlertsSent;

  public static final String JSON_PROPERTY_OLIGO_ID = "oligoId";
  private Long oligoId;

  public static final String JSON_PROPERTY_ORDERED_QUANTITY = "orderedQuantity";
  private BigDecimal orderedQuantity;

  public static final String JSON_PROPERTY_PACK_SIZE = "packSize";
  private String packSize;

  public static final String JSON_PROPERTY_PART_NUMBER = "partNumber";
  private String partNumber;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private BigDecimal quantity;

  public static final String JSON_PROPERTY_RECEIVED_QUANTITY = "receivedQuantity";
  private BigDecimal receivedQuantity;

  public static final String JSON_PROPERTY_REQUISITIONER_EMAIL = "requisitionerEmail";
  private String requisitionerEmail;

  public static final String JSON_PROPERTY_REQUISITIONER_NAME = "requisitionerName";
  private String requisitionerName;

  public static final String JSON_PROPERTY_SERVICE_INFO = "serviceInfo";
  private ServiceInfo serviceInfo;

  public static final String JSON_PROPERTY_SHIPPED_QUANTITY = "shippedQuantity";
  private BigDecimal shippedQuantity;

  public static final String JSON_PROPERTY_SUPPLIER_COMMENTS = "supplierComments";
  private String supplierComments;

  public static final String JSON_PROPERTY_SUPPLIER_PART_NUMBER = "supplierPartNumber";
  private String supplierPartNumber;

  public static final String JSON_PROPERTY_TAX_INFO = "taxInfo";
  private TaxInfo taxInfo;

  public static final String JSON_PROPERTY_UNIT_OF_MEASURE = "unitOfMeasure";
  private String unitOfMeasure;

  public static final String JSON_PROPERTY_UNIT_PRICE = "unitPrice";
  private BigDecimal unitPrice;


  public PurchaseOrderLine attachment(Attachment attachment) {
    
    this.attachment = attachment;
    return this;
  }

   /**
   * Get attachment
   * @return attachment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTACHMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Attachment getAttachment() {
    return attachment;
  }


  public void setAttachment(Attachment attachment) {
    this.attachment = attachment;
  }


  public PurchaseOrderLine attention(String attention) {
    
    this.attention = attention;
    return this;
  }

   /**
   * Get attention
   * @return attention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAttention() {
    return attention;
  }


  public void setAttention(String attention) {
    this.attention = attention;
  }


  public PurchaseOrderLine attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public PurchaseOrderLine cancelledQuantity(BigDecimal cancelledQuantity) {
    
    this.cancelledQuantity = cancelledQuantity;
    return this;
  }

   /**
   * Get cancelledQuantity
   * @return cancelledQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CANCELLED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCancelledQuantity() {
    return cancelledQuantity;
  }


  public void setCancelledQuantity(BigDecimal cancelledQuantity) {
    this.cancelledQuantity = cancelledQuantity;
  }


  public PurchaseOrderLine catalogueItemId(Long catalogueItemId) {
    
    this.catalogueItemId = catalogueItemId;
    return this;
  }

   /**
   * Get catalogueItemId
   * @return catalogueItemId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATALOGUE_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getCatalogueItemId() {
    return catalogueItemId;
  }


  public void setCatalogueItemId(Long catalogueItemId) {
    this.catalogueItemId = catalogueItemId;
  }


  public PurchaseOrderLine catalogueNumber(String catalogueNumber) {
    
    this.catalogueNumber = catalogueNumber;
    return this;
  }

   /**
   * Get catalogueNumber
   * @return catalogueNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATALOGUE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCatalogueNumber() {
    return catalogueNumber;
  }


  public void setCatalogueNumber(String catalogueNumber) {
    this.catalogueNumber = catalogueNumber;
  }


  public PurchaseOrderLine categoryName(String categoryName) {
    
    this.categoryName = categoryName;
    return this;
  }

   /**
   * Get categoryName
   * @return categoryName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategoryName() {
    return categoryName;
  }


  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }


  public PurchaseOrderLine classificationCode(ClassificationCode classificationCode) {
    
    this.classificationCode = classificationCode;
    return this;
  }

   /**
   * Get classificationCode
   * @return classificationCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CLASSIFICATION_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ClassificationCode getClassificationCode() {
    return classificationCode;
  }


  public void setClassificationCode(ClassificationCode classificationCode) {
    this.classificationCode = classificationCode;
  }


  public PurchaseOrderLine comments(String comments) {
    
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComments() {
    return comments;
  }


  public void setComments(String comments) {
    this.comments = comments;
  }


  public PurchaseOrderLine contractReferenceData(ContractReferenceData contractReferenceData) {
    
    this.contractReferenceData = contractReferenceData;
    return this;
  }

   /**
   * Get contractReferenceData
   * @return contractReferenceData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CONTRACT_REFERENCE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContractReferenceData getContractReferenceData() {
    return contractReferenceData;
  }


  public void setContractReferenceData(ContractReferenceData contractReferenceData) {
    this.contractReferenceData = contractReferenceData;
  }


  public PurchaseOrderLine currency(Currency currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Currency getCurrency() {
    return currency;
  }


  public void setCurrency(Currency currency) {
    this.currency = currency;
  }


  public PurchaseOrderLine customFields(List<CustomField> customFields) {
    
    this.customFields = customFields;
    return this;
  }

  public PurchaseOrderLine addCustomFieldsItem(CustomField customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new ArrayList<>();
    }
    this.customFields.add(customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomField> getCustomFields() {
    return customFields;
  }


  public void setCustomFields(List<CustomField> customFields) {
    this.customFields = customFields;
  }


  public PurchaseOrderLine dateRequired(OffsetDateTime dateRequired) {
    
    this.dateRequired = dateRequired;
    return this;
  }

   /**
   * Get dateRequired
   * @return dateRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATE_REQUIRED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateRequired() {
    return dateRequired;
  }


  public void setDateRequired(OffsetDateTime dateRequired) {
    this.dateRequired = dateRequired;
  }


  public PurchaseOrderLine description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PurchaseOrderLine disputedQuantity(BigDecimal disputedQuantity) {
    
    this.disputedQuantity = disputedQuantity;
    return this;
  }

   /**
   * Get disputedQuantity
   * @return disputedQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPUTED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getDisputedQuantity() {
    return disputedQuantity;
  }


  public void setDisputedQuantity(BigDecimal disputedQuantity) {
    this.disputedQuantity = disputedQuantity;
  }


  public PurchaseOrderLine externalComments(String externalComments) {
    
    this.externalComments = externalComments;
    return this;
  }

   /**
   * Get externalComments
   * @return externalComments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalComments() {
    return externalComments;
  }


  public void setExternalComments(String externalComments) {
    this.externalComments = externalComments;
  }


  public PurchaseOrderLine externalId(String externalId) {
    
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalId() {
    return externalId;
  }


  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  public PurchaseOrderLine grandTotal(BigDecimal grandTotal) {
    
    this.grandTotal = grandTotal;
    return this;
  }

   /**
   * Get grandTotal
   * @return grandTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GRAND_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getGrandTotal() {
    return grandTotal;
  }


  public void setGrandTotal(BigDecimal grandTotal) {
    this.grandTotal = grandTotal;
  }


  public PurchaseOrderLine id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public PurchaseOrderLine jppsgCode(String jppsgCode) {
    
    this.jppsgCode = jppsgCode;
    return this;
  }

   /**
   * Get jppsgCode
   * @return jppsgCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JPPSG_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJppsgCode() {
    return jppsgCode;
  }


  public void setJppsgCode(String jppsgCode) {
    this.jppsgCode = jppsgCode;
  }


  public PurchaseOrderLine lineTypeId(Long lineTypeId) {
    
    this.lineTypeId = lineTypeId;
    return this;
  }

   /**
   * Get lineTypeId
   * @return lineTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LINE_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLineTypeId() {
    return lineTypeId;
  }


  public void setLineTypeId(Long lineTypeId) {
    this.lineTypeId = lineTypeId;
  }


  public PurchaseOrderLine manufacturer(String manufacturer) {
    
    this.manufacturer = manufacturer;
    return this;
  }

   /**
   * Get manufacturer
   * @return manufacturer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MANUFACTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getManufacturer() {
    return manufacturer;
  }


  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }


  public PurchaseOrderLine netTotal(BigDecimal netTotal) {
    
    this.netTotal = netTotal;
    return this;
  }

   /**
   * Get netTotal
   * @return netTotal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NET_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNetTotal() {
    return netTotal;
  }


  public void setNetTotal(BigDecimal netTotal) {
    this.netTotal = netTotal;
  }


  public PurchaseOrderLine numberOfAlertsSent(BigDecimal numberOfAlertsSent) {
    
    this.numberOfAlertsSent = numberOfAlertsSent;
    return this;
  }

   /**
   * Get numberOfAlertsSent
   * @return numberOfAlertsSent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NUMBER_OF_ALERTS_SENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNumberOfAlertsSent() {
    return numberOfAlertsSent;
  }


  public void setNumberOfAlertsSent(BigDecimal numberOfAlertsSent) {
    this.numberOfAlertsSent = numberOfAlertsSent;
  }


  public PurchaseOrderLine oligoId(Long oligoId) {
    
    this.oligoId = oligoId;
    return this;
  }

   /**
   * Get oligoId
   * @return oligoId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OLIGO_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOligoId() {
    return oligoId;
  }


  public void setOligoId(Long oligoId) {
    this.oligoId = oligoId;
  }


  public PurchaseOrderLine orderedQuantity(BigDecimal orderedQuantity) {
    
    this.orderedQuantity = orderedQuantity;
    return this;
  }

   /**
   * Get orderedQuantity
   * @return orderedQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORDERED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getOrderedQuantity() {
    return orderedQuantity;
  }


  public void setOrderedQuantity(BigDecimal orderedQuantity) {
    this.orderedQuantity = orderedQuantity;
  }


  public PurchaseOrderLine packSize(String packSize) {
    
    this.packSize = packSize;
    return this;
  }

   /**
   * Get packSize
   * @return packSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PACK_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPackSize() {
    return packSize;
  }


  public void setPackSize(String packSize) {
    this.packSize = packSize;
  }


  public PurchaseOrderLine partNumber(String partNumber) {
    
    this.partNumber = partNumber;
    return this;
  }

   /**
   * Get partNumber
   * @return partNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PART_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPartNumber() {
    return partNumber;
  }


  public void setPartNumber(String partNumber) {
    this.partNumber = partNumber;
  }


  public PurchaseOrderLine quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getQuantity() {
    return quantity;
  }


  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  public PurchaseOrderLine receivedQuantity(BigDecimal receivedQuantity) {
    
    this.receivedQuantity = receivedQuantity;
    return this;
  }

   /**
   * Get receivedQuantity
   * @return receivedQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RECEIVED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getReceivedQuantity() {
    return receivedQuantity;
  }


  public void setReceivedQuantity(BigDecimal receivedQuantity) {
    this.receivedQuantity = receivedQuantity;
  }


  public PurchaseOrderLine requisitionerEmail(String requisitionerEmail) {
    
    this.requisitionerEmail = requisitionerEmail;
    return this;
  }

   /**
   * Get requisitionerEmail
   * @return requisitionerEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REQUISITIONER_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequisitionerEmail() {
    return requisitionerEmail;
  }


  public void setRequisitionerEmail(String requisitionerEmail) {
    this.requisitionerEmail = requisitionerEmail;
  }


  public PurchaseOrderLine requisitionerName(String requisitionerName) {
    
    this.requisitionerName = requisitionerName;
    return this;
  }

   /**
   * Get requisitionerName
   * @return requisitionerName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REQUISITIONER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequisitionerName() {
    return requisitionerName;
  }


  public void setRequisitionerName(String requisitionerName) {
    this.requisitionerName = requisitionerName;
  }


  public PurchaseOrderLine serviceInfo(ServiceInfo serviceInfo) {
    
    this.serviceInfo = serviceInfo;
    return this;
  }

   /**
   * Get serviceInfo
   * @return serviceInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERVICE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServiceInfo getServiceInfo() {
    return serviceInfo;
  }


  public void setServiceInfo(ServiceInfo serviceInfo) {
    this.serviceInfo = serviceInfo;
  }


  public PurchaseOrderLine shippedQuantity(BigDecimal shippedQuantity) {
    
    this.shippedQuantity = shippedQuantity;
    return this;
  }

   /**
   * Get shippedQuantity
   * @return shippedQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SHIPPED_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getShippedQuantity() {
    return shippedQuantity;
  }


  public void setShippedQuantity(BigDecimal shippedQuantity) {
    this.shippedQuantity = shippedQuantity;
  }


  public PurchaseOrderLine supplierComments(String supplierComments) {
    
    this.supplierComments = supplierComments;
    return this;
  }

   /**
   * Get supplierComments
   * @return supplierComments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPLIER_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupplierComments() {
    return supplierComments;
  }


  public void setSupplierComments(String supplierComments) {
    this.supplierComments = supplierComments;
  }


  public PurchaseOrderLine supplierPartNumber(String supplierPartNumber) {
    
    this.supplierPartNumber = supplierPartNumber;
    return this;
  }

   /**
   * Get supplierPartNumber
   * @return supplierPartNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SUPPLIER_PART_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupplierPartNumber() {
    return supplierPartNumber;
  }


  public void setSupplierPartNumber(String supplierPartNumber) {
    this.supplierPartNumber = supplierPartNumber;
  }


  public PurchaseOrderLine taxInfo(TaxInfo taxInfo) {
    
    this.taxInfo = taxInfo;
    return this;
  }

   /**
   * Get taxInfo
   * @return taxInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAX_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TaxInfo getTaxInfo() {
    return taxInfo;
  }


  public void setTaxInfo(TaxInfo taxInfo) {
    this.taxInfo = taxInfo;
  }


  public PurchaseOrderLine unitOfMeasure(String unitOfMeasure) {
    
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Get unitOfMeasure
   * @return unitOfMeasure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIT_OF_MEASURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnitOfMeasure() {
    return unitOfMeasure;
  }


  public void setUnitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }


  public PurchaseOrderLine unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Get unitPrice
   * @return unitPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIT_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseOrderLine purchaseOrderLine = (PurchaseOrderLine) o;
    return Objects.equals(this.attachment, purchaseOrderLine.attachment) &&
        Objects.equals(this.attention, purchaseOrderLine.attention) &&
        Objects.equals(this.attributes, purchaseOrderLine.attributes) &&
        Objects.equals(this.cancelledQuantity, purchaseOrderLine.cancelledQuantity) &&
        Objects.equals(this.catalogueItemId, purchaseOrderLine.catalogueItemId) &&
        Objects.equals(this.catalogueNumber, purchaseOrderLine.catalogueNumber) &&
        Objects.equals(this.categoryName, purchaseOrderLine.categoryName) &&
        Objects.equals(this.classificationCode, purchaseOrderLine.classificationCode) &&
        Objects.equals(this.comments, purchaseOrderLine.comments) &&
        Objects.equals(this.contractReferenceData, purchaseOrderLine.contractReferenceData) &&
        Objects.equals(this.currency, purchaseOrderLine.currency) &&
        Objects.equals(this.customFields, purchaseOrderLine.customFields) &&
        Objects.equals(this.dateRequired, purchaseOrderLine.dateRequired) &&
        Objects.equals(this.description, purchaseOrderLine.description) &&
        Objects.equals(this.disputedQuantity, purchaseOrderLine.disputedQuantity) &&
        Objects.equals(this.externalComments, purchaseOrderLine.externalComments) &&
        Objects.equals(this.externalId, purchaseOrderLine.externalId) &&
        Objects.equals(this.grandTotal, purchaseOrderLine.grandTotal) &&
        Objects.equals(this.id, purchaseOrderLine.id) &&
        Objects.equals(this.jppsgCode, purchaseOrderLine.jppsgCode) &&
        Objects.equals(this.lineTypeId, purchaseOrderLine.lineTypeId) &&
        Objects.equals(this.manufacturer, purchaseOrderLine.manufacturer) &&
        Objects.equals(this.netTotal, purchaseOrderLine.netTotal) &&
        Objects.equals(this.numberOfAlertsSent, purchaseOrderLine.numberOfAlertsSent) &&
        Objects.equals(this.oligoId, purchaseOrderLine.oligoId) &&
        Objects.equals(this.orderedQuantity, purchaseOrderLine.orderedQuantity) &&
        Objects.equals(this.packSize, purchaseOrderLine.packSize) &&
        Objects.equals(this.partNumber, purchaseOrderLine.partNumber) &&
        Objects.equals(this.quantity, purchaseOrderLine.quantity) &&
        Objects.equals(this.receivedQuantity, purchaseOrderLine.receivedQuantity) &&
        Objects.equals(this.requisitionerEmail, purchaseOrderLine.requisitionerEmail) &&
        Objects.equals(this.requisitionerName, purchaseOrderLine.requisitionerName) &&
        Objects.equals(this.serviceInfo, purchaseOrderLine.serviceInfo) &&
        Objects.equals(this.shippedQuantity, purchaseOrderLine.shippedQuantity) &&
        Objects.equals(this.supplierComments, purchaseOrderLine.supplierComments) &&
        Objects.equals(this.supplierPartNumber, purchaseOrderLine.supplierPartNumber) &&
        Objects.equals(this.taxInfo, purchaseOrderLine.taxInfo) &&
        Objects.equals(this.unitOfMeasure, purchaseOrderLine.unitOfMeasure) &&
        Objects.equals(this.unitPrice, purchaseOrderLine.unitPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachment, attention, attributes, cancelledQuantity, catalogueItemId, catalogueNumber, categoryName, classificationCode, comments, contractReferenceData, currency, customFields, dateRequired, description, disputedQuantity, externalComments, externalId, grandTotal, id, jppsgCode, lineTypeId, manufacturer, netTotal, numberOfAlertsSent, oligoId, orderedQuantity, packSize, partNumber, quantity, receivedQuantity, requisitionerEmail, requisitionerName, serviceInfo, shippedQuantity, supplierComments, supplierPartNumber, taxInfo, unitOfMeasure, unitPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseOrderLine {\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    attention: ").append(toIndentedString(attention)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    cancelledQuantity: ").append(toIndentedString(cancelledQuantity)).append("\n");
    sb.append("    catalogueItemId: ").append(toIndentedString(catalogueItemId)).append("\n");
    sb.append("    catalogueNumber: ").append(toIndentedString(catalogueNumber)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    classificationCode: ").append(toIndentedString(classificationCode)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    contractReferenceData: ").append(toIndentedString(contractReferenceData)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    dateRequired: ").append(toIndentedString(dateRequired)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    disputedQuantity: ").append(toIndentedString(disputedQuantity)).append("\n");
    sb.append("    externalComments: ").append(toIndentedString(externalComments)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    grandTotal: ").append(toIndentedString(grandTotal)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jppsgCode: ").append(toIndentedString(jppsgCode)).append("\n");
    sb.append("    lineTypeId: ").append(toIndentedString(lineTypeId)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    netTotal: ").append(toIndentedString(netTotal)).append("\n");
    sb.append("    numberOfAlertsSent: ").append(toIndentedString(numberOfAlertsSent)).append("\n");
    sb.append("    oligoId: ").append(toIndentedString(oligoId)).append("\n");
    sb.append("    orderedQuantity: ").append(toIndentedString(orderedQuantity)).append("\n");
    sb.append("    packSize: ").append(toIndentedString(packSize)).append("\n");
    sb.append("    partNumber: ").append(toIndentedString(partNumber)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    receivedQuantity: ").append(toIndentedString(receivedQuantity)).append("\n");
    sb.append("    requisitionerEmail: ").append(toIndentedString(requisitionerEmail)).append("\n");
    sb.append("    requisitionerName: ").append(toIndentedString(requisitionerName)).append("\n");
    sb.append("    serviceInfo: ").append(toIndentedString(serviceInfo)).append("\n");
    sb.append("    shippedQuantity: ").append(toIndentedString(shippedQuantity)).append("\n");
    sb.append("    supplierComments: ").append(toIndentedString(supplierComments)).append("\n");
    sb.append("    supplierPartNumber: ").append(toIndentedString(supplierPartNumber)).append("\n");
    sb.append("    taxInfo: ").append(toIndentedString(taxInfo)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

